name: Maven JUnit Tests

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Action to set up Java Development Kit
      with:
        java-version: '17' # Specify the Java version
        distribution: 'temurin' # Specify the Java distribution (e.g., Adoptium Temurin)
        cache: maven # Enable caching for Maven dependencies

    - name: Cache Maven packages
      uses: actions/cache@v4 # Action to cache files
      with:
        path: ~/.m2 # Path to the Maven local repository
        key: ${{ runner.os }}-maven-${{ hashFiles('keycloak-magic-link/pom.xml') }} # Cache key based on OS and pom.xml hash within the subfolder
        restore-keys: |
          ${{ runner.os }}-maven- # Fallback key for restoring cache

    - name: Install Playwright dependencies
      run: npx playwright install --with-deps # Install Playwright browsers and their system dependencies
      working-directory: keycloak-magic-link # Ensure this runs in the correct directory if Playwright needs local context

    - name: Run Maven tests
      run: mvn -B test # Run Maven tests in batch mode (-B) for non-interactive execution
      working-directory: keycloak-magic-link # Specify the working directory for this step
      # The 'test' goal compiles the test sources and runs the tests using the configured test framework (e.g., Surefire for JUnit)
